const container = document.getElementById('container'),
    form = document.getElementsByClassName('form')[0],
    formName = document.getElementById('fname'),
    playerSelected = document.getElementsByClassName('form__wrapper__select')[0],
    playerTypes = document.getElementsByClassName('form__wrapper__select-opts'),
    formButton = document.getElementsByClassName('form__wrapper__button')[0],
    characterButton = document.getElementsByClassName('form__wrapper__button-character')[0],
    characterMan = document.getElementsByClassName('character__man')[0],
    characterWater = document.getElementsByClassName('character__water')[0],
    skinsMan = document.getElementsByClassName('manSkins'),
    skinsWater = document.getElementsByClassName('waterSkins'),
    customise = document.getElementsByClassName('form__customise')[0],
    settings = document.getElementsByClassName('form__settings')[0],
    backToCustomiseButton = document.getElementsByClassName('backToCustomise')[0],
    permission = document.getElementsByClassName('permission')[0],
    muteIcon = document.getElementsByClassName('muteStatus'),
    introAudio = new Audio('assets/audio/intro_music.mp3'),
    p5Sounds = [new Audio('assets/audio/thunder.m4a'), new Audio('assets/audio/thunder_2.mp3'), new Audio('assets/audio/wolf.mp3')],
    buttonAudio = new Audio('assets/audio/buttonAudio.mp3'),
    rain = new Audio('assets/audio/rain.mp3'),
    bulletCountDisplay = document.getElementById('bulletCountDisplay'),
    bulletCountAnimation = document.getElementsByClassName('bulletCountAnimation')[0],
    menu = document.getElementsByClassName('menu')[0],
    burger = document.getElementsByClassName('burger')[0],
    side = document.getElementsByClassName('side')[0],
    headphone = document.getElementsByClassName('headphone')[0],
    navigation = document.getElementsByClassName('navigation')[0],
    man = document.getElementsByClassName('man__player')[0],
    water = document.getElementsByClassName('water__player')[0],
    filter = document.getElementsByClassName('filter')[0],
    emptyGun = new Audio("../../assets/audio/emptyGun.m4a"),
    gunSupressor = new Audio("../../assets/audio/gun_supressor.m4a"),
    sniper = new Audio("../../assets/audio/Gun2.mp3"),
    shotgun = new Audio("../../assets/audio/Gun3.mp3"),
    reloadPistol = new Audio("../../assets/audio/reload_pistol.mp3");
let chosenSideId,
    chosenPlayer,
    neglectedSideId,
    neglectedSide,
    playersJoined,
    permitAudio = false,
    ifMapSelected = false,
    menuStatus = false,
    otherPlayersExist,
    gameStroke = new THREE.MeshBasicMaterial({
        color: 0x000000,
        wireframe: true,
        wireframeLinewidth: 2,
    }),
    geo, mat,
    walls, grass, plane,
    texture,
    ambLights, sun, sky, lights,
    zone, environment,
    scope,
    bullets = [],
    playerId, player, otherPlayers = {},
    arenaSizeSelected, arenaSize,
    meshShrinkSpeed, shrinkSpeed = .01,
    stats,
    user = {},
    speedyStats = {
        type: 'speedy',
        health: 80,
        damage: 40,
        moveSpeed: .17,
        maxSpeed: .4,
        turnSpeed: .1,
        sprintTurnSpeed: .1,
        acceleration: .007,
        staminaDrain: .3,
        staminaRecovery: .025,
        fireSpeed: 7,
        bulletSize: .1,
        bulletSpeed: 2,
        magazineSize: 24,
        reloadSpeed: 3400,
        totalBullets: 120,
        scopeZoom: 3,
        dblScopeZoom: 2,
        bulletHeight: 1
    },
    assassinStats = {
        type: 'assassin',
        health: 60,
        damage: 88,
        moveSpeed: .14,
        maxSpeed: .25,
        turnSpeed: .07,
        sprintTurnSpeed: .05,
        acceleration: .2,
        staminaDrain: .6,
        staminaRecovery: .1,
        fireSpeed: 120,
        bulletSize: .4,
        bulletSpeed: 3.5,
        magazineSize: 16,
        reloadSpeed: 1600,
        totalBullets: 72,
        scopeZoom: 3,
        dblScopeZoom: 2,
        bulletHeight: 1
    },
    tankStats = {
        type: 'tank',
        health: 95,
        damage: 64,
        moveSpeed: .12,
        maxSpeed: .25,
        turnSpeed: .05,
        sprintTurnSpeed: .04,
        acceleration: .004,
        staminaDrain: .1,
        staminaRecovery: .02,
        fireSpeed: 60,
        bulletSize: 1,
        bulletSpeed: 1.5,
        magazineSize: 9,
        reloadSpeed: 5400,
        totalBullets: 45,
        scopeZoom: 3,
        dblScopeZoom: 2,
        bulletHeight: 1
    };

(() => {
    setTimeout(() => {
        permission.classList.add('permissionIn');
        filter.innerHTML = '';
        filter.style.display = 'none';
    }, 5000)
})()
